In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('train_new.csv')
data.tail()

month   day  year  Hour     CellName     Traffic
497539     10  22.0  2018    23  Cell_004072  2785.69977
497540     10  22.0  2018    23  Cell_004073  4270.04041
497541     10  22.0  2018    23  Cell_004081   461.19980
497542     10  22.0  2018    23  Cell_004082   439.44049
497543     10  22.0  2018    23  Cell_004083   331.21805

In [3]:
data.dropna(inplace = True)

In [4]:
cols = ['CellName']
for col in cols:
    data[col] = data[col].map(lambda x: str(x).lstrip('Cell_').rstrip('Cell_')).astype(float)

In [5]:
data.head()

month   day  year  Hour  CellName    Traffic
0     10  23.0  2017     7    1803.0   15.13867
1     10  23.0  2017     2    2303.0    2.05516
2     10  23.0  2017     7    4083.0   71.55308
3     10  23.0  2017     0    3781.0  557.98491
4     10  23.0  2017     3     112.0    0.98166

In [6]:
data = np.array(data)

In [7]:
traffic = data[:,-1]
cellname = data[:,-2]
hour = data[:,-3]
year = data[:,-4]
day = data[:,-5]
month = data[:,-6]

In [8]:
print(traffic.shape,hour.shape,year.shape,day.shape,month.shape)
np.transpose(traffic)
np.transpose(hour)
np.transpose(year)
np.transpose(day)
np.transpose(month)
print(traffic.shape,hour.shape,year.shape,day.shape,month.shape)

(497543,) (497543,) (497543,) (497543,) (497543,)
(497543,) (497543,) (497543,) (497543,) (497543,)


In [9]:
print(traffic , traffic[2])

[ 15.13867   2.05516  71.55308 ... 461.1998  439.44049 331.21805] 71.55308


In [10]:
tr = []
hr = []
yr = []
da = []
mo = []
for i in range(497542):
    for j in range(1,497542):
        if year[i]==year[j] and month[i]==month[j] and day[i]==day[j] and hour[i] == hour[j]:
            t = traffic[i]+traffic[j]
            tr.append(t)
            hr.append(hour[i])
            yr.append(year[i])
            da.append(day[i])
            mo.append(month[i])
        
    tr.append(traffic[i])
    hr.append(hour[i])
    yr.append(year[i])
    da.append(day[i])
    mo.append(month[i])

KeyboardInterrupt: 

In [11]:
print(tr)

[86.69175, 29.90776, 314.86069, 91.71473, 203.16592, 253.67999999999998, 355.77869, 382.89777, 15.13867, 66.22574, 27.08136, 42.05859, 499.71515999999997, 208.48275999999998, 147.47663, 16.27215, 68.59213, 140.57479, 150.01299, 33.96518, 29.875149999999998, 266.07221, 694.0182000000001, 17.2567, 60.395329999999994, 50.353649999999995, 107.99978, 23.882849999999998, 87.75074000000001, 232.93241, 60.40231, 29.53138, 607.20574, 36.53772, 24.85376, 298.55656999999997, 233.24678, 348.99617, 198.57592, 166.36803999999998, 32.65079, 35.39633, 52.719449999999995, 1003.72059, 28.44153, 22.00074, 90.63929, 70.81776, 21.56508, 112.79528, 50.61156, 113.96659000000001, 53.92185, 295.46347, 20.54264, 216.40051, 15.13867, 4.11032, 12.34844, 4.0590399999999995, 3.2306, 3.1597, 2.44738, 296.16396, 46.66959, 3.15351, 3.3495099999999995, 2.80992, 3.6776099999999996, 6.13171, 3.07253, 3.32951, 11.32311, 10.199279999999998, 20.42752, 29.37333, 90.15702, 2.33554, 4.62606, 11.934280000000001, 5.54669, 11.516

In [12]:
print(hr)

[7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,

In [34]:

data = data[:,1:]
data.astype('float32')

array([[7.0000000e+00, 1.8030000e+03, 1.5138670e+01],
       [2.0000000e+00, 2.3030000e+03, 2.0551600e+00],
       [7.0000000e+00, 4.0830000e+03, 7.1553078e+01],
       ...,
       [2.3000000e+01, 4.0810000e+03, 4.6119980e+02],
       [2.3000000e+01, 4.0820000e+03, 4.3944049e+02],
       [2.3000000e+01, 4.0830000e+03, 3.3121805e+02]], dtype=float32)

In [35]:
x = data[:,0:2]        # for all rows coloumn 0 ,1 as it doesnt take last number
y = data[:,-1]         # for all rows last coloumn
print(x.shape,y.shape)

(497544, 2) (497544,)


In [36]:
print(x[0:5,:])

[[7 1803.0]
 [2 2303.0]
 [7 4083.0]
 [0 3781.0]
 [3 112.0]]


In [37]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(x, y, test_size = 0.20, random_state = 5)

In [38]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)
print(lr.score(X_train, y_train)*100)
print(lr.score(X_val, y_val)*100)

16.231412928965383
16.239812232439157


In [39]:
from sklearn.ensemble import RandomForestRegressor
rt = RandomForestRegressor(n_estimators = 500, random_state = 0)
rt.fit(X_train,y_train)
print(rt.score(X_train, y_train)*100)
print(rt.score(X_val, y_val)*100)

KeyboardInterrupt: 

In [50]:
from sklearn.tree import DecisionTreeRegressor
dec_tree = DecisionTreeRegressor(random_state = 0)
dec_tree.fit(X_train,y_train)
print(rt.score(X_train, y_train)*100)
print(rt.score(X_val, y_val)*100)

IndexError: list index out of range

In [40]:
from keras.models import Sequential
from keras.layers import Dense
from keras import layers

In [41]:
no_features_columns = 2
no_target_columns = 1

In [42]:
model = Sequential()
model.add(Dense(32,activation ='relu' , input_shape = [no_features_columns]))
model.add(Dense(16,activation = 'relu'))
model.add(Dense(16,activation = 'relu'))
model.add(Dense(16,activation = 'relu'))
model.add(Dense(no_target_columns))

In [48]:
x =np.asarray(x).astype(np.int)

y =np.asarray(y).astype(np.int)

In [49]:
model.compile(loss='mean_absolute_error', optimizer='adam', metrics=['accuracy'])
model.fit(x, y, epochs=400, batch_size=50)

Epoch 1/400
9951/9951 [==============================] - 25s 1ms/step - loss: 404.5261 - accuracy: 0.0157
Epoch 2/400
9951/9951 [==============================] - 12s 1ms/step - loss: 382.9961 - accuracy: 0.0153
Epoch 3/400
9951/9951 [==============================] - 13s 1ms/step - loss: 380.0488 - accuracy: 0.0154
Epoch 4/400
9951/9951 [==============================] - 15s 2ms/step - loss: 380.2456 - accuracy: 0.0154
Epoch 5/400
9951/9951 [==============================] - 13s 1ms/step - loss: 379.2473 - accuracy: 0.0155
Epoch 6/400
9951/9951 [==============================] - 12s 1ms/step - loss: 377.7717 - accuracy: 0.0152
Epoch 7/400
9951/9951 [==============================] - 12s 1ms/step - loss: 377.7292 - accuracy: 0.0154
Epoch 8/400
9951/9951 [==============================] - 11s 1ms/step - loss: 378.8228 - accuracy: 0.0154
Epoch 9/400
9951/9951 [==============================] - 11s 1ms/step - loss: 376.2883 - accuracy: 0.0157
Epoch 10/400
9951/9951 [======================

9951/9951 [==============================] - 11s 1ms/step - loss: 364.6683 - accuracy: 0.0155
Epoch 153/400
9951/9951 [==============================] - 11s 1ms/step - loss: 362.3381 - accuracy: 0.0155
Epoch 154/400
9951/9951 [==============================] - 11s 1ms/step - loss: 365.4725 - accuracy: 0.0153
Epoch 155/400
9951/9951 [==============================] - 12s 1ms/step - loss: 363.7946 - accuracy: 0.0154
Epoch 156/400
9951/9951 [==============================] - 13s 1ms/step - loss: 363.5527 - accuracy: 0.0152
Epoch 157/400
9951/9951 [==============================] - 12s 1ms/step - loss: 363.3390 - accuracy: 0.0160
Epoch 158/400
9951/9951 [==============================] - 11s 1ms/step - loss: 363.4328 - accuracy: 0.0155
Epoch 159/400
9951/9951 [==============================] - 11s 1ms/step - loss: 364.0984 - accuracy: 0.0154
Epoch 160/400
9951/9951 [==============================] - 11s 1ms/step - loss: 364.4178 - accuracy: 0.0156
Epoch 161/400
9951/9951 [=================

Epoch 228/400
9951/9951 [==============================] - 11s 1ms/step - loss: 360.6770 - accuracy: 0.0155
Epoch 229/400
9951/9951 [==============================] - 11s 1ms/step - loss: 362.0473 - accuracy: 0.0152
Epoch 230/400
9951/9951 [==============================] - 11s 1ms/step - loss: 360.1513 - accuracy: 0.0153
Epoch 231/400
9951/9951 [==============================] - 11s 1ms/step - loss: 361.3301 - accuracy: 0.0155
Epoch 232/400
9951/9951 [==============================] - 11s 1ms/step - loss: 361.2326 - accuracy: 0.0153
Epoch 233/400
9951/9951 [==============================] - 10s 1ms/step - loss: 360.3188 - accuracy: 0.0153
Epoch 234/400
9951/9951 [==============================] - 10s 1ms/step - loss: 361.1354 - accuracy: 0.0153
Epoch 235/400
9951/9951 [==============================] - 11s 1ms/step - loss: 361.3458 - accuracy: 0.0155
Epoch 236/400
9951/9951 [==============================] - 11s 1ms/step - loss: 359.2769 - accuracy: 0.0155
Epoch 237/400
9951/9951 [===

Epoch 379/400
9951/9951 [==============================] - 12s 1ms/step - loss: 359.4107 - accuracy: 0.0155
Epoch 380/400
9951/9951 [==============================] - 11s 1ms/step - loss: 358.7251 - accuracy: 0.0154
Epoch 381/400
9951/9951 [==============================] - 11s 1ms/step - loss: 359.2467 - accuracy: 0.0158
Epoch 382/400
9951/9951 [==============================] - 14s 1ms/step - loss: 358.6798 - accuracy: 0.0155
Epoch 383/400
9951/9951 [==============================] - 14s 1ms/step - loss: 358.7375 - accuracy: 0.0154
Epoch 384/400
9951/9951 [==============================] - 13s 1ms/step - loss: 359.2534 - accuracy: 0.0154 0s
Epoch 385/400
9951/9951 [==============================] - 13s 1ms/step - loss: 359.3792 - accuracy: 0.0156
Epoch 386/400
9951/9951 [==============================] - 13s 1ms/step - loss: 358.3889 - accuracy: 0.0156
Epoch 387/400
9951/9951 [==============================] - 11s 1ms/step - loss: 359.2742 - accuracy: 0.0154
Epoch 388/400
9951/9951 [